"""Add ConjunctionHistory

Revision ID: 556c4a1524ff
Revises: c0207cd42600
Create Date: 2026-08-26 20:06:17.452062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556c4a1524ff'
down_revision: Union[str, Sequence[str], None] = 'c0207cd42600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conjunction_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conjunction_id', sa.String(), nullable=True),
    sa.Column('norad_id_1', sa.Integer(), nullable=True),
    sa.Column('norad_id_2', sa.Integer(), nullable=True),
    sa.Column('tca_prediction', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_dist_km', sa.Float(), nullable=True),
    sa.Column('relative_speed_km_s', sa.Float(), nullable=True),
    sa.Column('pc', sa.Float(), nullable=True),
    sa.Column('log10_pc', sa.Float(), nullable=True),
    sa.Column('covariance_model', sa.String(), nullable=True),
    sa.Column('tle_age_hours_1', sa.Float(), nullable=True),
    sa.Column('tle_age_hours_2', sa.Float(), nullable=True),
    sa.Column('model_agreement_score', sa.Float(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('event_status', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_pair', 'conjunction_history', ['norad_id_1', 'norad_id_2'], unique=False)
    op.create_index(op.f('ix_conjunction_history_conjunction_id'), 'conjunction_history', ['conjunction_id'], unique=False)
    op.create_index(op.f('ix_conjunction_history_norad_id_1'), 'conjunction_history', ['norad_id_1'], unique=False)
    op.create_index(op.f('ix_conjunction_history_norad_id_2'), 'conjunction_history', ['norad_id_2'], unique=False)
    op.create_index(op.f('ix_conjunction_history_recorded_at'), 'conjunction_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_conjunction_history_tca_prediction'), 'conjunction_history', ['tca_prediction'], unique=False)
    # op.create_foreign_key(None, 'conjunctions', 'run_metadata', ['run_id'], ['run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'conjunctions', type_='foreignkey')
    op.drop_index(op.f('ix_conjunction_history_tca_prediction'), table_name='conjunction_history')
    op.drop_index(op.f('ix_conjunction_history_recorded_at'), table_name='conjunction_history')
    op.drop_index(op.f('ix_conjunction_history_norad_id_2'), table_name='conjunction_history')
    op.drop_index(op.f('ix_conjunction_history_norad_id_1'), table_name='conjunction_history')
    op.drop_index(op.f('ix_conjunction_history_conjunction_id'), table_name='conjunction_history')
    op.drop_index('idx_history_pair', table_name='conjunction_history')
    op.drop_table('conjunction_history')
    # ### end Alembic commands ###
