"""Add runtime tracking to RunMetadata

Revision ID: 8123f1189c56
Revises: f1618233c156
Create Date: 2026-08-27 00:19:16.194417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8123f1189c56'
down_revision: Union[str, Sequence[str], None] = 'f1618233c156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_metadata', sa.Column('screening_runtime_seconds', sa.Float(), nullable=True))
    op.add_column('run_metadata', sa.Column('stage3_runtime_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_metadata', 'stage3_runtime_seconds')
    op.drop_column('run_metadata', 'screening_runtime_seconds')
    # ### end Alembic commands ###
