"""Add formal risk estimation fields

Revision ID: a34322d1a00d
Revises: df8c59627d9b
Create Date: 2026-08-26 19:36:21.131037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34322d1a00d'
down_revision: Union[str, Sequence[str], None] = 'df8c59627d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conjunctions', sa.Column('pc_lower', sa.Float(), nullable=True))
    op.add_column('conjunctions', sa.Column('pc_upper', sa.Float(), nullable=True))
    op.add_column('conjunctions', sa.Column('sensitivity_score', sa.Float(), nullable=True))
    op.add_column('conjunctions', sa.Column('uncertainty_confidence', sa.String(), nullable=True))
    op.add_column('conjunctions', sa.Column('foster_chan_agreement', sa.Float(), nullable=True))
    op.add_column('conjunctions', sa.Column('uncertainty_explanation', sa.String(), nullable=True))
    # op.create_foreign_key(None, 'conjunctions', 'run_metadata', ['run_id'], ['run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'conjunctions', type_='foreignkey')
    op.drop_column('conjunctions', 'uncertainty_explanation')
    op.drop_column('conjunctions', 'foster_chan_agreement')
    op.drop_column('conjunctions', 'uncertainty_confidence')
    op.drop_column('conjunctions', 'sensitivity_score')
    op.drop_column('conjunctions', 'pc_upper')
    op.drop_column('conjunctions', 'pc_lower')
    # ### end Alembic commands ###
