"""Add MC validation fields

Revision ID: c0207cd42600
Revises: a34322d1a00d
Create Date: 2026-08-26 19:48:51.762665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0207cd42600'
down_revision: Union[str, Sequence[str], None] = 'a34322d1a00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conjunctions', sa.Column('mc_pc', sa.Float(), nullable=True))
    op.add_column('conjunctions', sa.Column('mc_confidence_interval', sa.String(), nullable=True))
    op.add_column('conjunctions', sa.Column('mc_sample_count', sa.Integer(), nullable=True))
    op.add_column('conjunctions', sa.Column('mc_validation_status', sa.String(), nullable=True))
    op.add_column('conjunctions', sa.Column('mc_seed', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'conjunctions', 'run_metadata', ['run_id'], ['run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'conjunctions', type_='foreignkey')
    op.drop_column('conjunctions', 'mc_seed')
    op.drop_column('conjunctions', 'mc_validation_status')
    op.drop_column('conjunctions', 'mc_sample_count')
    op.drop_column('conjunctions', 'mc_confidence_interval')
    op.drop_column('conjunctions', 'mc_pc')
    # ### end Alembic commands ###
