"""Add RunMetadata and reproducibility fields

Revision ID: df8c59627d9b
Revises: c1f9d45e89a1
Create Date: 2026-08-26 19:28:58.697343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8c59627d9b'
down_revision: Union[str, Sequence[str], None] = 'c1f9d45e89a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_metadata',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=True),
    sa.Column('dataset_version', sa.String(), nullable=True),
    sa.Column('propagation_version', sa.String(), nullable=True),
    sa.Column('config_version', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_object_count', sa.Integer(), nullable=True),
    sa.Column('recomputed_event_count', sa.Integer(), nullable=True),
    sa.Column('reused_event_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.add_column('conjunctions', sa.Column('source_tles', sa.String(), nullable=True))
    op.add_column('conjunctions', sa.Column('propagation_model', sa.String(), nullable=True))
    op.add_column('conjunctions', sa.Column('stage_3_model', sa.String(), nullable=True))
    op.add_column('conjunctions', sa.Column('tca_convergence_status', sa.String(), nullable=True))
    op.add_column('conjunctions', sa.Column('refinement_tolerance', sa.Float(), nullable=True))
    op.add_column('conjunctions', sa.Column('pc_method', sa.String(), nullable=True))
    op.add_column('conjunctions', sa.Column('covariance_model', sa.String(), nullable=True))
    op.add_column('conjunctions', sa.Column('hbr_model', sa.String(), nullable=True))
    op.add_column('conjunctions', sa.Column('filter_decisions', sa.String(), nullable=True))
    op.add_column('conjunctions', sa.Column('model_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conjunctions', sa.Column('run_id', sa.String(), nullable=True))
    op.add_column('conjunctions', sa.Column('dataset_version', sa.String(), nullable=True))
    op.add_column('conjunctions', sa.Column('propagation_version', sa.String(), nullable=True))
    op.add_column('conjunctions', sa.Column('config_version', sa.String(), nullable=True))
    op.create_index(op.f('ix_conjunctions_run_id'), 'conjunctions', ['run_id'], unique=False)
    # op.create_foreign_key(None, 'conjunctions', 'run_metadata', ['run_id'], ['run_id'])
    op.add_column('space_objects', sa.Column('tle_epoch', sa.DateTime(timezone=True), nullable=True))
    op.add_column('space_objects', sa.Column('tle_age_hours', sa.Float(), nullable=True))
    op.add_column('space_objects', sa.Column('source', sa.String(), nullable=True))
    op.add_column('space_objects', sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('space_objects', sa.Column('propagation_status', sa.String(), nullable=True))
    op.add_column('space_objects', sa.Column('sgp4_error_code', sa.Integer(), nullable=True))
    op.add_column('space_objects', sa.Column('launch_designator', sa.String(), nullable=True))
    op.add_column('space_objects', sa.Column('data_quality_score', sa.Float(), nullable=True))
    op.add_column('space_objects', sa.Column('data_quality_grade', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space_objects', 'data_quality_grade')
    op.drop_column('space_objects', 'data_quality_score')
    op.drop_column('space_objects', 'launch_designator')
    op.drop_column('space_objects', 'sgp4_error_code')
    op.drop_column('space_objects', 'propagation_status')
    op.drop_column('space_objects', 'source_timestamp')
    op.drop_column('space_objects', 'source')
    op.drop_column('space_objects', 'tle_age_hours')
    op.drop_column('space_objects', 'tle_epoch')
    # op.drop_constraint(None, 'conjunctions', type_='foreignkey')
    op.drop_index(op.f('ix_conjunctions_run_id'), table_name='conjunctions')
    op.drop_column('conjunctions', 'config_version')
    op.drop_column('conjunctions', 'propagation_version')
    op.drop_column('conjunctions', 'dataset_version')
    op.drop_column('conjunctions', 'run_id')
    op.drop_column('conjunctions', 'model_timestamp')
    op.drop_column('conjunctions', 'filter_decisions')
    op.drop_column('conjunctions', 'hbr_model')
    op.drop_column('conjunctions', 'covariance_model')
    op.drop_column('conjunctions', 'pc_method')
    op.drop_column('conjunctions', 'refinement_tolerance')
    op.drop_column('conjunctions', 'tca_convergence_status')
    op.drop_column('conjunctions', 'stage_3_model')
    op.drop_column('conjunctions', 'propagation_model')
    op.drop_column('conjunctions', 'source_tles')
    op.drop_table('run_metadata')
    # ### end Alembic commands ###
