"""Add operational threat ranking fields

Revision ID: f1618233c156
Revises: 556c4a1524ff
Create Date: 2026-08-26 23:51:34.041525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1618233c156'
down_revision: Union[str, Sequence[str], None] = '556c4a1524ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conjunctions', sa.Column('threat_score', sa.Float(), nullable=True))
    op.add_column('conjunctions', sa.Column('risk_category', sa.String(length=50), nullable=True))
    op.add_column('conjunctions', sa.Column('threat_factors', sa.JSON(), nullable=True))
    op.add_column('conjunctions', sa.Column('threat_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conjunctions', 'threat_version')
    op.drop_column('conjunctions', 'threat_factors')
    op.drop_column('conjunctions', 'risk_category')
    op.drop_column('conjunctions', 'threat_score')
    # ### end Alembic commands ###
